#' HAL function from the package hal9001
#'
#' @returns A design matrix representing the expanded set of binary indicator functions of the covariates
#' @details The hal_model() function simply calls the fit_hal() function from the hal9001 R package and only returns the matrix of binary indicator basis function that is generated by the Highly Adaptive Lasso algorithm. 
#' @export
hal_model<- function(X, Y, max_degree, num_knots, nfolds, foldid){
  # fitting HAL
  mod_full<- fit_hal(X=X,
                     Y=Y,
                     X_unpenalized = NULL,
                     max_degree = max_degree,
                     smoothness_orders = 0,
                     num_knots = num_knots,
                     reduce_basis = 0.01,
                     family = c("binomial"),
                     lambda = 10,
                     id = NULL,
                     offset = NULL,
                     fit_control = list(cv_select = FALSE, nfolds = nfolds, foldid = foldid, use_min = TRUE,
                                        lambda.min.ratio = .001, prediction_bounds = "default"),
                     basis_list = NULL,
                     return_lasso = TRUE,
                     return_x_basis = TRUE,
                     yolo = FALSE)
  ## design matrix
  x_basis_full<- mod_full$x_basis[,-1] ## first column is intercept term (all ones)
  return(x_basis_full)
}